language: php
php:
    - '5.6'
    - '7.0'
install:
    - composer require nette/nette:${NETTE_VERSION}
env:
    - NETTE_VERSION="~2.3.0"
    - NETTE_VERSION="~2.4.0"
script:
    - vendor/bin/tester -p php -c tests/php.ini -o console --coverage tests/coverage.xml --coverage-src src tests/
after_script:
  - vendor/bin/codacycoverage clover tests/coverage.xml
